### ISSUE TITLE
Add addtional html for the form input

### ISSUE THREAD

**Issue by anandasubedi** [kristijanhusak/laravel-form-builder#32]
Is there any posibility to add additional html to form inputs . for instance , I would like to add a span on label to make it a required filed 
<label> Name <span class="required">*</span></label>

**Comment by kristijanhusak** [comment]
You can do that easily with css with `:after`.
```css
label.required:after {
    content: " *";
}
```
