### ISSUE TITLE
Filters?

### ISSUE THREAD

**Issue by ryanscherler** [kristijanhusak/laravel-form-builder#398]
It seems there is the ability to set filters along with rules for a field. How is this used? Are there examples somewhere of using a filter? - and can there be custom filters added (would love to have an html filter that uses Purifier or something of the sort). 

Also, is it possible to have a custom class based  rule in addition to the already included laravel defined rules?

**Comment by kristijanhusak** [comment]
Yeah, docs are not up to date for that. You have some examples on the PR where it was added.
https://github.com/kristijanhusak/laravel-form-builder/pull/376

For the custom class based rule, you can use a closure , but only on dev-master at the moment. It wasn't really properly tested. https://github.com/kristijanhusak/laravel-form-builder/issues/386#issuecomment-338810915

**Comment by ryanscherler** [comment]
I eventually got the hang of how to use them by taking a look at existing filters and the part of the code that resolves them

I am actually working on a YAML configuration based form builder for the app we are working on, and just pass in something like the following to use a custom filter (along with a new custom field we setup for Redactor WYSIWYG editor)

```yml
bio:
    type: redactor
    options:
      label: Bio
      attr:
        rows: 5
      filters: 
        - \App\Filters\HTML
      settings:
        formatting: [p,h2,h3]
```

and custom filter:

```php
namespace \App\Filters;

use Kris\LaravelFormBuilder\Filters\FilterInterface;
use Purifier;

class HTML implements FilterInterface
{
    /**
     * @param mixed $value
     * @param array $options
     *
     * @return mixed
     */
    public function filter($value, $options = [])
    {
        $config = empty($options) ? $options : null;
        return Purifier::clean($value, $config);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'HTML';
    }
}
```

Thanks for all your hard work on this project, its really a lifesaver for us - as most all of this app we are creating depends on custom fields defined and YAML and executed by your form builder package. ;-)

**Comment by ryanscherler** [comment]
One thing as a follow up that I haven't been able to figure out - is how to 'pass' filter options in when declaring the filter as a class (or even string) etc. via YAML. Something like:

```yml
bio:
    type: redactor
    options:
      label: Bio
      attr:
        rows: 5
      filters: 
        - \App\Filters\HTML($options)?
      settings:
        formatting: [p,h2,h3]
```
